#!/usr/bin/env python3
"""One-time migration: add <link rel="preload" as="style"> hints for the 10
stylesheets v1-shell.css @imports, so the browser's preload scanner starts
fetching them immediately from the HTML parse instead of waiting ~70ms for
v1-shell.css itself to download and parse before it can even discover their
URLs (measured live on production via the Resource Timing API: the 6 direct
<link> stylesheets all start at ~87ms; the 10 @import-chained ones don't
start until ~160ms). That gap is a real, measurable cause of the "old design
flashes for an instant before the new one appears" symptom on reload: the
page paints once with only the 6 base stylesheets applied, then again once
the @import chain resolves ~73ms later.

Deliberately NOT removing the @import chain itself or the v1-shell.css
<link> tag: several existing tests assert the chain's content directly
(tests/test-pr95-editorial-system.mjs reads assets/v1-shell.css and checks
it @imports specific files) and five page-generating builders emit that
exact <link> line. Preloading is additive and doesn't disturb any of that --
once preloaded, the @import's own request for the same URL resolves from
the browser's preload cache instead of hitting the network again.
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

IMPORTED = (
    "v1-shell-base.css",
    "v1-shell-lrb-v2.css",
    "v1-lrb-material-v2.css",
    "v1-home-editorial-v3.css",
    "v1-editorial-interior-v4.css",
    "v1-editorial-placeholders-v4.css",
    "v1-editorial-interactions-v4.css",
    "v1-banner-art-direction-v5.css",
    "v1-site-cohesion-v6.css",
    "v1-reflow-hardening-v7.css",
)

START = "<!-- v1-shell-preload:start (generated by scripts/add_v1_shell_preloads.py -- do not edit by hand) -->"
END = "<!-- v1-shell-preload:end -->"

# Matches just the <link ...v1-shell.css... /> tag itself -- not anchored to
# a whole line, since several builder-generated pages emit every <link> back
# to back on one minified line with no newlines between them. A single,
# bounded tag match with no wildcard spanning multiple tags -- no multi-line
# backtracking risk like an earlier regex mistake this session.
TAG_RE = re.compile(r'<link rel="stylesheet" href="(/?)assets/v1-shell\.css"\s*/?>')
MARKER_RE = re.compile(r"[ \t]*" + re.escape(START) + r"[\s\S]*?" + re.escape(END) + r"\n?")


def preload_block(indent: str, leading_slash: str) -> str:
    lines = [f'{indent}{START}']
    for name in IMPORTED:
        lines.append(f'{indent}<link rel="preload" as="style" href="{leading_slash}assets/{name}" />')
    lines.append(f'{indent}{END}')
    return "\n".join(lines) + "\n"


def line_indent_before(text: str, pos: int) -> tuple[int, str] | None:
    """Returns (line_start_offset, indent) for the whitespace between the
    last newline and `pos`, or None if there is non-whitespace content on
    that line before `pos` (a minified page with several tags sharing one
    line), or if there is no real indent to reuse (empty prefix) -- caller
    falls back to a fixed default in both cases. Excluding the empty-prefix
    case matters for idempotency: after this script's own block is stripped
    and re-derived, a page that had no indent still has an empty prefix, so
    treating "" as a reusable indent would make the two passes disagree."""
    line_start = text.rfind("\n", 0, pos) + 1
    prefix = text[line_start:pos]
    return (line_start, prefix) if prefix != "" and prefix.strip() == "" else None


def tracked_html(root: Path) -> list[Path]:
    out = subprocess.run(
        ["git", "ls-files", "-z", "*.html"], cwd=root, capture_output=True, text=True, check=True,
    ).stdout
    return [root / rel for rel in out.split("\0") if rel]


def process(path: Path, check: bool) -> str | None:
    """Returns the relative path if changed (or would change), else None."""
    original = path.read_text(encoding="utf-8")
    text = original
    if MARKER_RE.search(text):
        # Idempotent re-run: drop the old block, regenerate fresh below.
        text = MARKER_RE.sub("", text)

    match = TAG_RE.search(text)
    if not match:
        return None

    leading_slash = match.group(1)
    found = line_indent_before(text, match.start())
    if found is None:
        # Minified page (tag shares its line with others, or the previous
        # line has no real indent to reuse): insert the block as its own
        # lines right before the tag, with exactly one newline joining each
        # side regardless of whether the text up to here already ends in
        # one -- required for idempotency, since after this script's own
        # block is stripped, the preceding text DOES already end in "\n".
        prefix = text[: match.start()]
        needs_leading_newline = not prefix.endswith("\n")
        block = preload_block("  ", leading_slash)
        text = prefix + ("\n" if needs_leading_newline else "") + block + text[match.start():]
    else:
        # The tag has its own line with a real (non-empty) indent, e.g. "  ".
        # That indent is reused for every inserted line AND for the tag's
        # own line, which starts right where the indent did -- so replace
        # from line_start (before the indent), not from match.start() (after
        # it), or the original indent and the block's first line would
        # double up.
        line_start, indent = found
        block = preload_block(indent, leading_slash)
        text = text[:line_start] + block + indent + text[match.start():]

    if text == original:
        return None
    if not check:
        path.write_text(text, encoding="utf-8")
    return path.relative_to(ROOT).as_posix()


def main() -> int:
    check = "--check" in sys.argv
    changed = []
    for path in sorted(tracked_html(ROOT)):
        rel = path.relative_to(ROOT).as_posix()
        if rel.startswith("lab/"):
            continue
        result = process(path, check)
        if result:
            changed.append(result)

    if check and changed:
        print("FAIL: v1-shell preload hints missing/outdated in:", file=sys.stderr)
        for item in changed:
            print(f" - {item}", file=sys.stderr)
        return 1

    mode = "CHECK" if check else "GENERATED"
    print(f"{mode}: {len(changed)} page(s) touched")
    for item in changed:
        print(f" - {item}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
