#!/usr/bin/env python3
"""Generate V1 shell blocks from data/navigation.json + content-registry.json.

This builder keeps three shell blocks in sync across all authored V1 pages:
- header (`<header class=\"site-header\" ...>`)
- explore dialog (`<dialog class=\"explore-dialog\" ...>`)
- footer (`<footer class=\"site-footer\">`)

It follows the same marker + --check workflow used by other builders in this
repository.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
NAV_PATH = ROOT / "data" / "navigation.json"
REGISTRY_PATH = ROOT / "data" / "content-registry.json"
EXTRAS_PATH = ROOT / "data" / "site-shell-extras.json"

HEADER_START = "<!-- site-shell:header:start (generated by scripts/build-site-shell.py -- do not edit by hand) -->"
HEADER_END = "<!-- site-shell:header:end -->"
DIALOG_START = "<!-- site-shell:dialog:start (generated by scripts/build-site-shell.py -- do not edit by hand) -->"
DIALOG_END = "<!-- site-shell:dialog:end -->"
FOOTER_START = "<!-- site-shell:footer:start (generated by scripts/build-site-shell.py -- do not edit by hand) -->"
FOOTER_END = "<!-- site-shell:footer:end -->"

SHELL_PAGE_RE = re.compile(r"<html[^>]*\bclass=\"[^\"]*\bv1\b")
FOOTER_RE = re.compile(r"<footer class=\"site-footer\"[\s\S]*?</footer>", re.I)
HEADER_RE = re.compile(r"<header class=\"site-header[^\"]*\"[\s\S]*?</header>", re.I)
DIALOG_RE = re.compile(r"<dialog class=\"explore-dialog\"[\s\S]*?</dialog>", re.I)
CANONICAL_RE = re.compile(r"<link\s+[^>]*rel=\"canonical\"[^>]*href=\"([^\"]+)\"", re.I)

SOCIAL_ROW = (
    '<div class="social-row">'
    '<a class="social-icon" href="https://www.instagram.com/davidportodiaz/" target="_blank" rel="noopener noreferrer me" aria-label="Instagram" title="Instagram"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true" focusable="false"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="3.8"/><circle cx="17.3" cy="6.7" r="0.6" fill="currentColor" stroke="none"/></svg></a>'
    '<a class="social-icon" href="https://www.facebook.com/profile.php?id=61590793667301" target="_blank" rel="noopener noreferrer me" aria-label="Facebook" title="Facebook"><svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" focusable="false"><path d="M16.7 3H7.3A4.3 4.3 0 0 0 3 7.3v9.4A4.3 4.3 0 0 0 7.3 21h4.2v-6.6H9.4v-2.6h2.1V9.8c0-2.1 1.3-3.3 3.2-3.3.9 0 1.7.1 1.9.1v2.2h-1.3c-1 0-1.2.5-1.2 1.2v1.7h2.4l-.3 2.6h-2.1V21h2.6a4.3 4.3 0 0 0 4.3-4.3V7.3A4.3 4.3 0 0 0 16.7 3z"/></svg></a>'
    '<a class="social-icon" href="https://www.tiktok.com/@davidportoescritor" target="_blank" rel="noopener noreferrer me" aria-label="TikTok" title="TikTok"><svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" focusable="false"><path d="M14 3c.4 2.2 2 3.8 4.2 4.1v2.7c-1.5 0-2.9-.4-4.1-1.2v6.1a4.9 4.9 0 1 1-4.2-4.9v2.7a2.2 2.2 0 1 0 1.6 2.1V3h2.5z"/></svg></a>'
    '<a class="social-icon" href="https://www.threads.net/@davidportodiaz" target="_blank" rel="noopener noreferrer me" aria-label="Threads" title="Threads"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true" focusable="false"><path d="M12 21c4.4 0 7-2.8 7-7.5C19 8 16.5 4 12 4 8 4 5.5 6.8 5.5 11c0 3 1.8 4.8 4.3 4.8 2 0 3.4-1.2 3.4-3 0-1.4-.9-2.3-2.1-2.3-.9 0-1.5.5-1.7 1.2"/></svg></a>'
    '<a class="social-icon" href="https://bsky.app/profile/davidportoescritor.bsky.social" target="_blank" rel="noopener noreferrer me" aria-label="Bluesky" title="Bluesky"><svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" focusable="false"><path d="M12 7c-1.6-2.3-4.6-3.6-6.7-3.2-.3 2.3.4 5.4 2 7.1-1.6.1-2.8.8-3 1.7.7.9 2.3 1.3 3.8 1-.9 1.1-1.1 2.6-.5 3.8 1.6.1 3.7-1.1 4.6-2.8.4 1 .9 1.9 1.5 2.6.6-.7 1.1-1.6 1.5-2.6.9 1.7 3 2.9 4.6 2.8.6-1.2.4-2.7-.5-3.8 1.5.3 3.1-.1 3.8-1-.2-.9-1.4-1.6-3-1.7 1.6-1.7 2.3-4.8 2-7.1-2.1-.4-5.1.9-6.7 3.2-.2.3-.4.6-.5 1-.1-.4-.3-.7-.5-1z"/></svg></a>'
    '<a class="social-icon" href="https://www.pinterest.com/davidportodiaz/" target="_blank" rel="noopener noreferrer me" aria-label="Pinterest" title="Pinterest"><svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" focusable="false"><path d="M12 2C6.5 2 3 5.6 3 10c0 3.2 1.8 5.1 3 5.7.2.1.4 0 .4-.3l.4-1.5c0-.2 0-.3-.1-.5-.4-.5-.7-1.4-.7-2.3 0-3 2.2-5.7 5.8-5.7 3.1 0 4.9 1.9 4.9 4.5 0 3.4-1.5 5.6-3.5 5.6-1.1 0-2-.9-1.7-2.1.3-1.3.9-2.7.9-3.7 0-.8-.5-1.5-1.4-1.5-1.1 0-2 1.2-2 2.7 0 1 .3 1.7.3 1.7s-1.2 4.9-1.4 5.8c-.4 1.6-.1 3.6 0 3.8.1.1.2.1.3 0 .1-.2 1.5-1.9 2-3.5.1-.4.6-2.3.6-2.3.3.6 1.2 1.1 2.2 1.1 2.9 0 5-2.7 5-6.4C20 5.7 16.5 2 12 2z"/></svg></a>'
    '<a class="social-icon" href="https://www.linkedin.com/in/davidportodiaz/" target="_blank" rel="noopener noreferrer me" aria-label="LinkedIn" title="LinkedIn"><svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" focusable="false"><path d="M5 3a2 2 0 1 0 0 4 2 2 0 0 0 0-4zM3.5 9h3v12h-3V9zm6.5 0h2.9v1.6c.5-.9 1.7-1.9 3.4-1.9 3.6 0 4.6 2.3 4.6 5.4V21h-3v-6.1c0-1.5-.5-2.5-1.9-2.5-1.4 0-2 1-2 2.4V21h-3V9z"/></svg></a>'
    '<a class="text-action" href="https://www.goodreads.com/author/show/66843136.David_Porto_D_az" target="_blank" rel="noopener noreferrer">Goodreads</a>'
    "</div>"
)

PREVIEW_COPY = {
    "works-hub": "Las dos novelas publicadas, fragmentos y rutas de lectura.",
    "notebook-hub": "Artículos y piezas editoriales sobre proceso y lecturas.",
    "tools-hub": "Utilidades gratuitas para problemas concretos de escritura.",
    "author": "Biografía, trayectoria y páginas de contexto del autor.",
    "press": "Material de prensa, agenda y apariciones verificables.",
    "site-map": "Índice completo para recorrer todo el sitio por secciones.",
}


@dataclass(frozen=True)
class Entry:
    item_id: str
    url: str
    label: str
    short_label: str
    source_file: str


class BuildError(RuntimeError):
    pass


def load_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise BuildError(f"No se pudo leer {path.relative_to(ROOT)}: {exc}") from exc


def canonical_path_from_html(text: str) -> str | None:
    match = CANONICAL_RE.search(text)
    if not match:
        return None
    path = urlparse(match.group(1)).path
    return path or "/"


# Páginas V1 que a propósito NO llevan el shell. Tienen que estar declaradas
# aquí una por una, con su motivo: una página V1 que no esté ni generada ni
# exenta hace fallar el build. Sin esta lista, cualquier página se salía del
# contrato con solo no tener `<footer class="site-footer">`, y el check pasaba
# igual — que es exactamente el modo de fallo que este builder venía a cerrar.
SHELL_EXEMPT = {
    # Superficie para IA/desarrollo, sin shell de lectura. Su cabecera reducida
    # (Obra · Autor · Prensa) es deliberada y por eso queda fuera del contrato.
    "ai/index.html": "superficie para IA: cabecera propia, sin pie de navegación",
    # Documento que se sirve dentro de un iframe: el shell lo pone la página
    # anfitriona, repetirlo aquí duplicaría cabecera y pie dentro del marco.
    "asistente/embed.html": "documento embebido en iframe: el shell lo pone la página anfitriona",
}


def tracked_html(root: Path) -> list[Path]:
    """Ficheros HTML versionados, preguntándoselo a git.

    Recorrer el disco mete ficheros que en CI no existen (`.preview-dist/`,
    carpetas de trabajo sin versionar) y deja el gate comportándose distinto
    en local y en CI. Ya pasó con el gate de reflow.
    """
    out = subprocess.run(
        ["git", "ls-files", "-z", "*.html"],
        cwd=root, capture_output=True, text=True, check=True,
    ).stdout
    return [root / rel for rel in out.split("\0") if rel]


def collect_shell_pages(root: Path) -> tuple[list[Path], list[str]]:
    """Devuelve (páginas con shell, páginas V1 que se han saltado el contrato)."""
    pages: list[Path] = []
    escapees: list[str] = []
    for path in sorted(tracked_html(root)):
        rel = path.relative_to(root).as_posix()
        if rel.startswith("lab/"):
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        if not SHELL_PAGE_RE.search(text):
            continue
        if FOOTER_RE.search(text):
            pages.append(path)
        elif rel not in SHELL_EXEMPT:
            escapees.append(rel)
    return pages, escapees


def ensure_registry(registry_raw: dict) -> dict[str, Entry]:
    defaults = registry_raw.get("defaults", {})
    entries_raw = registry_raw.get("entries", [])
    out: dict[str, Entry] = {}
    for raw in entries_raw:
        merged = {**defaults, **raw}
        out[merged["id"]] = Entry(
            item_id=merged["id"],
            url=merged["url"],
            label=merged["label"],
            short_label=merged["shortLabel"],
            source_file=merged["sourceFile"],
        )
    return out


def link(entry: Entry, current_path: str) -> str:
    aria = ' aria-current="page"' if entry.url == current_path else ""
    return f'<a href="{entry.url}"{aria}>{entry.short_label}</a>'


def render_header(nav: dict, by_id: dict[str, Entry], current_path: str) -> str:
    links = "\n".join(f"        {link(by_id[item_id], current_path)}" for item_id in nav["header"])
    return (
        '<header class="site-header" data-header>\n'
        '  <div class="site-header__inner">\n'
        '    <a class="brand" href="/" aria-label="David Porto Díaz — inicio">\n'
        '      <span class="brand__name">David Porto Díaz</span>\n'
        '      <span class="brand__role">Escritor</span>\n'
        '    </a>\n'
        '    <nav class="primary-nav" aria-label="Navegación principal">\n'
        f"{links}\n"
        '    </nav>\n'
        '    <button class="explore-trigger" type="button" aria-haspopup="dialog" aria-controls="explore-dialog" aria-expanded="false" data-explore-open>\n'
        '      Explorar\n'
        '    </button>\n'
        '  </div>\n'
        '</header>'
    )


def render_explore_rows(nav: dict, by_id: dict[str, Entry]) -> list[tuple[str, str, str, str | None]]:
    rows: list[tuple[str, str, str, str | None]] = []
    for item in nav.get("exploreTerritories", []):
        entry = by_id[item["id"]]
        copy = PREVIEW_COPY.get(item["id"], entry.label)
        rows.append((entry.url, entry.short_label, copy, item["id"]))
    for item in nav.get("exploreShortcuts", []):
        target = by_id[item["targetId"]]
        rows.append((target.url, item["label"], target.label, item["targetId"]))
    for item_id in nav.get("exploreUtilities", []):
        entry = by_id[item_id]
        rows.append((entry.url, entry.short_label, entry.label, item_id))
    return rows


def render_explore(nav: dict, by_id: dict[str, Entry], current_path: str) -> str:
    rows = render_explore_rows(nav, by_id)
    current_entry = next((entry for entry in by_id.values() if entry.url == current_path), None)
    default_key = current_entry.item_id if current_entry and current_entry.item_id in PREVIEW_COPY else (rows[0][3] if rows else "works-hub")
    default_label = by_id[default_key].short_label if default_key in by_id else "Explorar"
    default_copy = PREVIEW_COPY.get(default_key, "Destinos clave de la web.")

    row_markup: list[str] = []
    for index, (href, title, text, preview_id) in enumerate(rows, 1):
        preview_attr = f' data-preview="{preview_id}"' if preview_id else ""
        row_markup.append(
            f'          <a class="explore-row" href="{href}"{preview_attr}>\n'
            f'            <span class="explore-row__index">{index:02d}</span>\n'
            f'            <span class="explore-row__body"><strong>{title}</strong><small>{text}</small></span>\n'
            '          </a>'
        )

    return (
        '<dialog class="explore-dialog" id="explore-dialog" aria-labelledby="explore-title" data-explore-dialog>\n'
        '  <div class="explore-dialog__shell">\n'
        '    <div class="explore-dialog__head">\n'
        '      <div>\n'
        '        <p class="eyebrow">Índice general</p>\n'
        '        <h2 id="explore-title">Explorar</h2>\n'
        '      </div>\n'
        '      <button class="icon-button" type="button" aria-label="Cerrar Explorar" data-explore-close>\n'
        '        <svg aria-hidden="true" viewBox="0 0 24 24" width="20" height="20"><path d="M5 5l14 14M19 5L5 19"/></svg>\n'
        '      </button>\n'
        '    </div>\n\n'
        '    <div class="explore-dialog__grid">\n'
        '      <nav class="explore-list" aria-label="Destinos de la web">\n'
        + "\n".join(row_markup)
        + '\n      </nav>\n\n'
        '      <aside class="explore-preview" data-explore-preview>\n'
        '        <div class="explore-preview__media" aria-hidden="true" data-preview-media></div>\n'
        f'        <p class="explore-preview__label" data-preview-label>{default_label}</p>\n'
        f'        <p class="explore-preview__copy" data-preview-copy>{default_copy}</p>\n'
        '      </aside>\n'
        '    </div>\n'
        '  </div>\n'
        '</dialog>'
    )


def footer_groups_with_extras(nav: dict, by_id: dict[str, Entry], extras: dict, rel_path: str) -> dict[str, list[Entry]]:
    groups: dict[str, list[Entry]] = {}
    for group_name, ids in nav.get("footer", {}).items():
        groups[group_name] = [by_id[item_id] for item_id in ids]

    for extra in extras.get("footerNavExtras", {}).values():
        if rel_path not in extra.get("pages", []):
            continue
        group = extra["group"]
        entry = by_id[extra["id"]]
        groups.setdefault(group, [])
        if entry.item_id not in {x.item_id for x in groups[group]}:
            groups[group].append(entry)
    return groups


def render_footer(nav: dict, by_id: dict[str, Entry], extras: dict, rel_path: str, current_path: str) -> str:
    groups = footer_groups_with_extras(nav, by_id, extras, rel_path)
    cols: list[str] = [
        '      <div>\n'
        '        <strong class="brand__name">David Porto Díaz</strong>\n'
        '        <p>Autor de Las manecillas del recuerdo y Samuel entre mundos.</p>\n'
        f'        {SOCIAL_ROW}\n'
        '      </div>'
    ]
    for group_name, entries in groups.items():
        links = "".join(link(entry, current_path) for entry in entries)
        cols.append(f'      <nav aria-label="{group_name}"><h2>{group_name}</h2>{links}</nav>')

    legal = [
        '      <span>© 2026 David Porto Díaz. Todos los derechos reservados.</span>'
    ]
    if rel_path in extras.get("footerLegalAffiliatePages", []):
        legal.append(
            '      <span>Algunos enlaces de compra son de afiliado del <a href="/aviso-legal.html#afiliado">programa Amazon Associates</a> (tag: davidporto-21).</span>'
        )

    return (
        '<footer class="site-footer">\n'
        '  <div class="site-footer__grid">\n'
        + "\n".join(cols)
        + '\n  </div>\n'
        '  <p class="footer-legal">\n'
        + "\n".join(legal)
        + '\n  </p>\n'
        '</footer>'
    )


def with_markers(block: str, start: str, end: str) -> str:
    return f"{start}\n{block}\n{end}"


def replace_or_insert_block(text: str, regex: re.Pattern[str], generated: str, start: str, end: str) -> tuple[str, bool]:
    marker_pattern = re.compile(re.escape(start) + r"[\s\S]*?" + re.escape(end))
    wrapped = with_markers(generated, start, end)
    if marker_pattern.search(text):
        return marker_pattern.sub(wrapped, text, count=1), True
    if regex.search(text):
        return regex.sub(wrapped, text, count=1), True
    return text, False


def process_page(path: Path, nav: dict, by_id: dict[str, Entry], extras: dict, check: bool) -> tuple[bool, bool]:
    original = path.read_text(encoding="utf-8", errors="replace")
    rel_path = path.relative_to(ROOT).as_posix()
    current_path = canonical_path_from_html(original) or ("/" if rel_path == "index.html" else "/" + rel_path.replace("index.html", ""))

    new_text = original
    header_html = render_header(nav, by_id, current_path)
    dialog_html = render_explore(nav, by_id, current_path)
    footer_html = render_footer(nav, by_id, extras, rel_path, current_path)

    new_text, ok_header = replace_or_insert_block(new_text, HEADER_RE, header_html, HEADER_START, HEADER_END)
    if not ok_header:
        raise BuildError(f"{rel_path}: no se encontró cabecera para inyectar shell")

    new_text, ok_dialog = replace_or_insert_block(new_text, DIALOG_RE, dialog_html, DIALOG_START, DIALOG_END)
    if not ok_dialog:
        pos = new_text.find(HEADER_END)
        if pos == -1:
            raise BuildError(f"{rel_path}: no se pudo insertar diálogo Explorar")
        insert_at = new_text.find("\n", pos)
        if insert_at == -1:
            insert_at = pos + len(HEADER_END)
        new_text = new_text[: insert_at + 1] + with_markers(dialog_html, DIALOG_START, DIALOG_END) + "\n\n" + new_text[insert_at + 1 :]

    new_text, ok_footer = replace_or_insert_block(new_text, FOOTER_RE, footer_html, FOOTER_START, FOOTER_END)
    if not ok_footer:
        raise BuildError(f"{rel_path}: no se encontró pie para inyectar shell")

    changed = new_text != original
    if changed and not check:
        path.write_text(new_text, encoding="utf-8")
    return changed, check and changed


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="No escribe; falla si hay páginas desactualizadas")
    args = parser.parse_args()

    nav = load_json(NAV_PATH)
    registry = ensure_registry(load_json(REGISTRY_PATH))
    extras = load_json(EXTRAS_PATH)

    pages, escapees = collect_shell_pages(ROOT)
    if not pages:
        raise BuildError("No se encontraron páginas shell")
    if escapees:
        raise BuildError(
            "páginas V1 sin shell y sin declarar en SHELL_EXEMPT: "
            + ", ".join(escapees)
            + " — o llevan el shell, o se declaran exentas con su motivo"
        )

    changed: list[str] = []
    for page in pages:
        page_changed, outdated = process_page(page, nav, registry, extras, check=args.check)
        if page_changed:
            changed.append(page.relative_to(ROOT).as_posix())
        if outdated:
            continue

    if args.check and changed:
        print("FAIL: shell desactualizado en:", file=sys.stderr)
        for item in changed:
            print(f" - {item}", file=sys.stderr)
        return 1

    mode = "CHECK" if args.check else "GENERATED"
    print(f"{mode}: shell en {len(pages)} páginas")
    if changed:
        print(f"CHANGED: {len(changed)}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except BuildError as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        raise SystemExit(1)
