#!/usr/bin/env python3
"""Reproducible "site in numbers" block: books, articles, tools, sample words.

Only counts things a machine can verify against the repository itself:
- indexable pages under libros/*/, cuaderno/*/, herramientas/*/ (real
  canonical required, no noindex);
- words inside explicit data-public-sample blocks (free-sample text the
  author marked as public).

No traffic, sales, follower or reader counts — those aren't reproducible
from the repo and are explicitly out of scope (see
27_REPOSITORIOS_Y_MEJORAS_IMPLEMENTABLES_2026-08-16.md and
60_ESTADISTICAS_HUMANAS_SITIO_INVESTIGACION_E_IMPLEMENTACION_2026-08-19.md).

Usage:
  # Render the fragment (for inspection) and write JSON alongside it:
  python scripts/build-human-site-stats.py --root . \
      --output data/site-human-stats.generated.html \
      --json-output data/site-human-stats.generated.json

  # Inject the fragment into a real page between markers, in place:
  python scripts/build-human-site-stats.py --root . \
      --output data/site-human-stats.generated.html \
      --json-output data/site-human-stats.generated.json \
      --inject-into autor.html

  # Verify everything is up to date (CI/pre-commit style), writes nothing:
  python scripts/build-human-site-stats.py --root . \
      --output data/site-human-stats.generated.html \
      --json-output data/site-human-stats.generated.json \
      --inject-into autor.html --check
"""
from __future__ import annotations

import argparse
import html
import json
import re
import sys
from dataclasses import dataclass
from datetime import date
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import urlparse

CANONICAL_RE = re.compile(r'<link\s+[^>]*rel=["\']canonical["\'][^>]*href=["\']([^"\']+)', re.I)
ROBOTS_RE = re.compile(r'<meta\s+[^>]*name=["\']robots["\'][^>]*content=["\']([^"\']+)', re.I)
WORD_RE = re.compile(r"[\wÀ-ÖØ-öø-ÿ]+(?:['’\-][\wÀ-ÖØ-öø-ÿ]+)*", re.UNICODE)

MARKER_START = '<!-- human-site-stats:start (generated by scripts/build-human-site-stats.py — do not edit by hand) -->'
MARKER_END = '<!-- human-site-stats:end -->'


@dataclass(frozen=True)
class Page:
    path: Path
    canonical: str


class SampleParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.depth = 0
        self.parts: list[str] = []

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if self.depth:
            self.depth += 1
        elif 'data-public-sample' in attrs:
            self.depth = 1

    def handle_endtag(self, tag):
        if self.depth:
            self.depth -= 1

    def handle_data(self, data):
        if self.depth:
            self.parts.append(data)


def read_text(path: Path) -> str:
    return path.read_text(encoding='utf-8', errors='replace')


def is_indexable(text: str) -> bool:
    match = ROBOTS_RE.search(text)
    if not match:
        return True
    tokens = {x.strip().lower() for x in match.group(1).split(',')}
    return 'noindex' not in tokens


def canonical(text: str) -> str | None:
    match = CANONICAL_RE.search(text)
    return match.group(1).strip() if match else None


def collect_indexable(root: Path, pattern: str) -> list[Page]:
    pages: list[Page] = []
    seen: dict[str, Path] = {}
    for path in sorted(root.glob(pattern)):
        text = read_text(path)
        if not is_indexable(text):
            continue
        can = canonical(text)
        if not can:
            raise ValueError(f'{path}: página indexable sin canonical')
        parsed = urlparse(can)
        if parsed.scheme != 'https' or parsed.netloc not in {'davidportodiaz.com', 'www.davidportodiaz.com'}:
            raise ValueError(f'{path}: canonical fuera del dominio canónico: {can}')
        if can in seen:
            raise ValueError(f'canonical duplicado: {can} en {seen[can]} y {path}')
        seen[can] = path
        pages.append(Page(path, can))
    return pages


def count_sample_words(root: Path) -> tuple[int, int]:
    total = 0
    blocks = 0
    for path in sorted(root.rglob('*.html')):
        if 'WEB DAVID PORTO nuevas ideas' in path.parts:
            continue
        text = read_text(path)
        if 'data-public-sample' not in text or not is_indexable(text):
            continue
        parser = SampleParser()
        parser.feed(text)
        if parser.parts:
            blocks += 1
            total += len(WORD_RE.findall(' '.join(parser.parts)))
    return total, blocks


def stats(root: Path) -> list[dict]:
    books = collect_indexable(root, 'libros/*/index.html')
    articles = collect_indexable(root, 'cuaderno/*/index.html')
    tools = collect_indexable(root, 'herramientas/*/index.html')
    sample_words, sample_blocks = count_sample_words(root)

    out = [
        {'key': 'books', 'label': 'Libros publicados', 'value': len(books), 'method': 'Páginas indexables bajo /libros/*/.'},
        {'key': 'articles', 'label': 'Artículos del Cuaderno', 'value': len(articles), 'method': 'Páginas indexables bajo /cuaderno/*/.'},
        {'key': 'tools', 'label': 'Herramientas gratuitas', 'value': len(tools), 'method': 'Páginas indexables bajo /herramientas/*/.'},
    ]
    if sample_blocks and sample_words:
        out.append({'key': 'sample_words', 'label': 'Palabras de lectura gratuita', 'value': sample_words, 'method': f'Texto visible dentro de {sample_blocks} bloque(s) data-public-sample.'})
    return [item for item in out if item['value'] > 0]


def render(items: list[dict], generated_on: str) -> str:
    if not items:
        raise ValueError('No hay estadísticas publicables (>0).')
    cards = ''.join(
        f'<div class="human-stat"><dt>{html.escape(str(i["value"]))}</dt><dd>{html.escape(i["label"])}</dd></div>'
        for i in items
    )
    methods = ''.join(f'<li><strong>{html.escape(i["label"])}</strong>: {html.escape(i["method"])}</li>' for i in items)
    return (
        '<section class="human-stats" aria-labelledby="human-stats-title">\n'
        '  <div class="human-stats__head">\n'
        '    <p class="eyebrow">Esta web, en cifras</p>\n'
        '    <h2 id="human-stats-title">Lo que ya puedes encontrar aquí.</h2>\n'
        '  </div>\n'
        f'  <dl class="human-stats__grid">{cards}</dl>\n'
        '  <details class="human-stats__method"><summary>Cómo se calculan</summary>\n'
        f'    <p>Generadas el {html.escape(generated_on)} desde contenido público del repositorio. No son métricas de audiencia ni una señal de ranking.</p><ul>{methods}</ul>\n'
        '  </details>\n'
        '</section>\n'
    )


def inject(target: Path, fragment: str, check: bool) -> int:
    if not target.exists():
        print(f'FAIL: {target} no existe', file=sys.stderr)
        return 1
    text = read_text(target)
    if MARKER_START not in text or MARKER_END not in text:
        print(f'FAIL: {target} no contiene los marcadores {MARKER_START!r} / {MARKER_END!r}', file=sys.stderr)
        return 1
    pattern = re.compile(re.escape(MARKER_START) + r'.*?' + re.escape(MARKER_END), re.S)
    replacement = f'{MARKER_START}\n{fragment}{MARKER_END}'
    new_text, count = pattern.subn(replacement, text, count=1)
    if count != 1:
        print(f'FAIL: no se pudo sustituir el bloque en {target}', file=sys.stderr)
        return 1
    if check:
        if new_text != text:
            print(f'FAIL: {target} desactualizado respecto a las estadísticas actuales', file=sys.stderr)
            return 1
        return 0
    target.write_text(new_text, encoding='utf-8')
    print(f'INJECTED: {target}')
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--root', required=True, type=Path)
    ap.add_argument('--output', required=True, type=Path)
    ap.add_argument('--json-output', type=Path)
    ap.add_argument('--inject-into', type=Path, help='Página donde sustituir el bloque entre marcadores human-site-stats:start/end')
    ap.add_argument('--date', default=date.today().isoformat())
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()

    root = args.root.resolve()
    items = stats(root)
    markup = render(items, args.date)
    payload = json.dumps({'generated_on': args.date, 'stats': items}, ensure_ascii=False, indent=2) + '\n'

    if args.check:
        ok = True
        if not args.output.exists() or read_text(args.output) != markup:
            print('FAIL: HTML desactualizado', file=sys.stderr)
            ok = False
        if args.json_output and (not args.json_output.exists() or read_text(args.json_output) != payload):
            print('FAIL: JSON desactualizado', file=sys.stderr)
            ok = False
        if args.inject_into:
            if inject(args.inject_into, markup, check=True) != 0:
                ok = False
        if not ok:
            return 1
        print(f'PASS: {len(items)} estadísticas reproducibles')
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(markup, encoding='utf-8')
    if args.json_output:
        args.json_output.parent.mkdir(parents=True, exist_ok=True)
        args.json_output.write_text(payload, encoding='utf-8')
    if args.inject_into:
        rc = inject(args.inject_into, markup, check=False)
        if rc != 0:
            return rc
    print(f'GENERATED: {len(items)} estadísticas')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
