#!/usr/bin/env python3
"""Generate assets/editorial-public-facts.mjs from editorial-facts.json.

editorial-facts.json is the internal editorial source of truth and stays out
of the public dist (scripts/build-public-dist.py excludes data/ and root-level
internal JSON). This generator projects only the subset of those facts that
the assistant's canned answers (assets/assistant-local-knowledge.mjs) are
allowed to state publicly, so a change to a canonical fact (a publication
date, an ISBN, an award year) propagates automatically instead of drifting
against a hand-written sentence.

Deliberately NOT projected: knownEditorialIncident (internal printing-error
tracking), editorialCopyNote / note / verifiedAt / sourceUrl provenance
fields not needed for a public answer, and anything else not listed in
PUBLIC_FIELDS below. Adding a new field to the projection is a deliberate
edit to this script, not automatic.

Usage:
    python scripts/build-public-editorial-facts.py [--check]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FACTS_PATH = ROOT / "editorial-facts.json"
OUTPUT_PATH = ROOT / "assets" / "editorial-public-facts.mjs"

MESES = [
    "enero", "febrero", "marzo", "abril", "mayo", "junio",
    "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre",
]


def human_date_es(iso_date: str) -> str:
    year, month, day = iso_date.split("-")
    return f"{int(day)} de {MESES[int(month) - 1]} de {year}"


def build_projection(facts: dict) -> dict:
    man = facts["books"]["lasManecillasDelRecuerdo"]
    sam = facts["books"]["samuelEntreMundos"]
    award = facts["recognitions"]["letrasComoEspada2026"]
    finalist = facts["recognitions"]["juanAndresTeno2026"]

    manecillas_available = man["purchaseUrl"] is not None
    return {
        "manecillas": {
            "title": man["title"],
            "publisher": man["publisher"],
            "publicationDate": man["publicationDate"],
            "publicationDateHuman": human_date_es(man["publicationDate"]),
            "isbn": man["isbn"],
            "numberOfPages": man["numberOfPages"],
            "priceEUR": man["priceEUR"],
            "purchaseUrl": man["purchaseUrl"],
            "availabilityNote": (
                man["purchaseUrl"] if manecillas_available else "Sin URL de compra verificada"
            ),
        },
        "samuel": {
            "title": sam["title"],
            "publisher": sam["publisher"],
            "publicationYear": sam["publicationYear"],
            "isbn": sam["isbn"],
            "numberOfPages": sam["numberOfPages"],
            "asin": sam["asin"],
            "purchaseUrls": dict(sam["purchaseUrls"]),
        },
        "recognitions": {
            "letrasComoEspada": {
                "result": award["result"],
                "name": award["name"],
                "organizer": award["organizer"],
                "year": award["year"],
                "holder": award["holder"],
                "submittedWork": award["submittedWork"],
            },
            "juanAndresTeno": {
                "result": finalist["result"],
                "name": finalist["name"],
                "organizer": finalist["organizer"],
                "year": finalist["year"],
                "holder": finalist["holder"],
                "submittedWork": finalist["submittedWork"],
                "sourceLimitation": finalist["sourceLimitation"],
            },
        },
    }


def render(projection: dict) -> str:
    body = json.dumps(projection, ensure_ascii=False, indent=2)
    return (
        "// AUTO-GENERATED by scripts/build-public-editorial-facts.py from editorial-facts.json.\n"
        "// Do not edit this file manually -- edit editorial-facts.json and regenerate.\n"
        "// Public projection only: excludes knownEditorialIncident and other internal-only fields.\n"
        f"export const EDITORIAL_PUBLIC_FACTS = {body};\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify output is up to date without writing")
    parser.add_argument("--facts", type=Path, default=FACTS_PATH, help="path to editorial-facts.json (default: repo root)")
    parser.add_argument("--output", type=Path, default=OUTPUT_PATH, help="path to write the generated .mjs (default: assets/editorial-public-facts.mjs)")
    args = parser.parse_args()

    facts = json.loads(args.facts.read_text(encoding="utf-8"))
    projection = build_projection(facts)
    rendered = render(projection)

    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.exists() else None
        if current != rendered:
            print(f"FAIL: {args.output} is stale. Regenerate with: python scripts/build-public-editorial-facts.py")
            return 1
        print(f"PASS: {args.output} matches {args.facts.name}")
        return 0

    args.output.write_text(rendered, encoding="utf-8")
    print(f"WROTE: {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
