#!/usr/bin/env python3
"""Generate the pre-rendered `.section-context` local-nav strip.

`assets/v1-editorial-interior-v4.js`'s `buildContextNav()` inserts a
`<nav class="section-context">` right after `.site-header` on every V1 page
whose path matches one of its `contexts` entries -- a JS-after-paint
insertion that pushes `<main>` down without reserving its space first. #129
fixed this for 5 pages by hand-copying the JS's output into static HTML (the
script's own `document.querySelector('.section-context')` guard then makes
it a no-op there). This builder does the same thing for every page that
matches a context, generated instead of hand-copied, so it can cover all of
them at once and stay correct as pages are added.

CONTEXTS below mirrors the `contexts` array in
assets/v1-editorial-interior-v4.js by hand (same convention as that file's
own comment mirroring data/navigation.json's `localNavSets`) -- keep both in
sync when either changes. `qa/section-context-parity.mjs` diffs this
builder's output against what the JS actually generates, so drift between
the two fails CI instead of silently reappearing as CLS.

Follows the same marker + --check workflow as build-site-shell.py.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]

NAV_START = "<!-- section-context:start (generated by scripts/build-section-context-nav.py -- do not edit by hand) -->"
NAV_END = "<!-- section-context:end -->"
HEADER_END_MARKER = "<!-- site-shell:header:end -->"

# This builder's own marker pair (regeneration case): both ends are exact
# literals, so the non-greedy middle can only ever match the single span
# between one specific start/end pair -- safe.
MARKER_PAIR_RE = re.compile(re.escape(NAV_START) + r"[\s\S]*?" + re.escape(NAV_END))
# The bare old, hand-authored PR#129 <nav class="section-context"> element
# itself, deliberately NOT trying to also swallow a preceding comment in the
# same regex -- an earlier version tried `(?:<!--[\s\S]*?-->\s*)?` in front
# of this and it backtracked across every unrelated "-->" in the whole
# document, from the first HTML comment in <head> through to this element,
# deleting everything in between. A stray preceding comment (each of the 5
# already-fixed pages worded its own by hand, no two alike) is instead
# stripped by strip_preceding_comment() below, which only ever looks at the
# single comment immediately adjacent to this match, never backtracks past
# an unrelated "-->" elsewhere in the file.
BARE_NAV_RE = re.compile(r"<nav class=\"section-context\"[\s\S]*?</nav>")


def strip_preceding_comment(text: str, start: int) -> int:
    before = text[:start]
    stripped = before.rstrip()
    if not stripped.endswith("-->"):
        return start
    comment_end = len(stripped)
    comment_start = before.rfind("<!--", 0, comment_end)
    if comment_start == -1:
        return start
    inner = before[comment_start + 4 : comment_end - 3]
    if "-->" in inner:
        return start  # more than one comment back-to-back -- leave alone
    return comment_start
CANONICAL_RE = re.compile(r'<link\s+[^>]*rel="canonical"[^>]*href="([^"]+)"', re.I)
HTML_TAG_RE = re.compile(r"<html\b[^>]*>", re.I)
V1_CLASS_RE = re.compile(r'\bclass="[^"]*\bv1\b')
EDITORIAL_CONTEXT_ATTR_RE = re.compile(r'\sdata-editorial-context="[^"]*"')


@dataclass(frozen=True)
class Context:
    key: str
    label: str
    home: str
    prefixes: tuple[str, ...]
    exacts: tuple[str, ...]
    links: tuple[tuple[str, str], ...]

    def matches(self, path: str) -> bool:
        return path in self.exacts or any(path.startswith(p) for p in self.prefixes)


# Order matters: first match wins, same as `contexts.find(...)` in the JS.
CONTEXTS: tuple[Context, ...] = (
    Context(
        key="manecillas", label="Manecillas", home="/las-manecillas-del-recuerdo/",
        prefixes=("/las-manecillas-del-recuerdo/",), exacts=(),
        links=(
            ("/libros/", "← Obras"),
            ("/las-manecillas-del-recuerdo/", "La novela"),
            ("/las-manecillas-del-recuerdo/fragmentos/", "Fragmentos"),
            ("/prensa.html#ficha-manecillas", "Ficha de prensa"),
        ),
    ),
    Context(
        key="samuel", label="Samuel entre mundos", home="/libros/samuel-entre-mundos/",
        prefixes=(
            "/libros/samuel-entre-mundos/",
            "/universo/noveris/",
            "/clubes-de-lectura/samuel-entre-mundos/",
        ),
        exacts=("/fragmento/",),
        links=(
            ("/libros/", "← Obras"),
            ("/libros/samuel-entre-mundos/", "El libro"),
            ("/fragmento/", "Capítulo 1"),
            ("/universo/noveris/", "Noveris"),
            ("/clubes-de-lectura/samuel-entre-mundos/", "Club de lectura"),
            ("/clubes-de-lectura/samuel-entre-mundos/guia-imprimible/", "Guía imprimible"),
        ),
    ),
    Context(
        key="obras", label="Obras", home="/libros/",
        prefixes=(), exacts=("/libros/",),
        links=(
            ("/libros/", "Todas las obras"),
            ("/las-manecillas-del-recuerdo/", "Las manecillas del recuerdo"),
            ("/libros/samuel-entre-mundos/", "Samuel entre mundos"),
        ),
    ),
    Context(
        key="cuaderno", label="Cuaderno", home="/cuaderno/",
        prefixes=("/cuaderno/", "/recomendaciones/"), exacts=(),
        links=(
            ("/cuaderno/", "Archivo"),
            ("/cuaderno/temas/", "Temas"),
            ("/recomendaciones/", "Recomendaciones"),
        ),
    ),
    Context(
        key="herramientas", label="Herramientas", home="/herramientas/",
        prefixes=(
            "/herramientas/",
            "/editoriales/",
            "/convocatorias-escritores/",
            "/metodologia-editorial/",
        ),
        exacts=(),
        links=(
            ("/herramientas/", "Herramientas"),
            ("/editoriales/", "Editoriales"),
            ("/convocatorias-escritores/", "Convocatorias"),
            ("/metodologia-editorial/", "Metodología"),
        ),
    ),
    Context(
        key="autor", label="Autor", home="/autor.html",
        prefixes=("/lectores-beta/",), exacts=("/autor.html", "/premios.html"),
        links=(
            ("/autor.html", "Autor"),
            ("/premios.html", "Premios"),
            ("/lectores-beta/", "Lectores beta"),
            ("/eventos.html", "Eventos"),
            ("/prensa.html", "Prensa"),
        ),
    ),
    Context(
        key="prensa", label="Prensa y agenda", home="/prensa.html",
        prefixes=(), exacts=("/prensa.html", "/eventos.html", "/ferias.html"),
        links=(
            ("/prensa.html", "Prensa"),
            ("/eventos.html", "Eventos"),
            ("/ferias.html", "Ferias"),
            ("/premios.html", "Premios"),
        ),
    ),
)


class BuildError(RuntimeError):
    pass


def normalise(path: str) -> str:
    path = re.sub(r"/index\.html$", "/", path)
    if len(path) > 1 and not path.endswith("/") and not path.lower().endswith(".html"):
        path += "/"
    return path


def find_context(current_path: str) -> Context | None:
    return next((c for c in CONTEXTS if c.matches(current_path)), None)


def score_links(context: Context, current_path: str) -> tuple[list[dict], dict | None]:
    scored = []
    for href, label in context.links:
        link_path = normalise(urlparse(href).path or href)
        exact = current_path == link_path
        family = (not exact) and link_path.endswith("/") and link_path != "/" and current_path.startswith(link_path)
        scored.append({"href": href, "label": label, "link_path": link_path, "exact": exact, "family": family})
    exact_match = next((s for s in scored if s["exact"]), None)
    best_family = None
    if not exact_match:
        candidates = [s for s in scored if s["family"]]
        if candidates:
            best_family = max(candidates, key=lambda s: len(s["link_path"]))
    return scored, exact_match or best_family


def render_nav(context: Context, current_path: str) -> str:
    scored, current_item = score_links(context, current_path)
    aria_current = ' aria-current="page"'
    links_html = "".join(
        f'<a href="{item["href"]}"{aria_current if item is current_item else ""}>{item["label"]}</a>'
        for item in scored
    )
    explanation = (
        "<!-- Pre-rendered to match assets/v1-editorial-interior-v4.js's buildContextNav()\n"
        "     output exactly (same classes/links/aria-current) for this page's context, so\n"
        "     it paints in its final position/size on first paint instead of being inserted\n"
        "     after the header post-load -- that JS insertion is a CLS source (see\n"
        "     docs/FINAL-CLOSURE-AUDIT-2026-08-27.md). The script's own\n"
        "     `document.querySelector('.section-context')` guard makes it a no-op once this\n"
        "     markup exists. Edit CONTEXTS in scripts/build-section-context-nav.py, not this\n"
        "     output; regenerate with `python scripts/build-section-context-nav.py`. -->"
    )
    nav = (
        f'<nav class="section-context" aria-label="Navegación de {context.label}" '
        f'data-editorial-context-nav="{context.key}"><div class="section-context__inner">'
        f'<a class="section-context__title" href="{context.home}">{context.label}</a>'
        f'<div class="section-context__links">{links_html}</div></div></nav>'
    )
    return f"{explanation}\n{nav}"


def canonical_path_from_html(text: str) -> str | None:
    match = CANONICAL_RE.search(text)
    if not match:
        return None
    return urlparse(match.group(1)).path or "/"


def tracked_html(root: Path) -> list[Path]:
    out = subprocess.run(
        ["git", "ls-files", "-z", "*.html"],
        cwd=root, capture_output=True, text=True, check=True,
    ).stdout
    return [root / rel for rel in out.split("\0") if rel]


def set_editorial_context_attr(html_tag: str, key: str) -> str:
    replacement = f'data-editorial-context="{key}"'
    if EDITORIAL_CONTEXT_ATTR_RE.search(html_tag):
        return EDITORIAL_CONTEXT_ATTR_RE.sub(f" {replacement}", html_tag, count=1)
    return html_tag[:-1] + f' {replacement}>' if html_tag.endswith(">") else html_tag


def apply_page(original: str, rel_path: str) -> str | None:
    """Returns the updated text, or None if this page isn't a V1 page with a
    context match (nothing to do -- not an error)."""
    html_match = HTML_TAG_RE.search(original)
    if not html_match or not V1_CLASS_RE.search(html_match.group(0)):
        return None

    current_path = normalise(canonical_path_from_html(original) or (
        "/" if rel_path == "index.html" else "/" + rel_path.replace("index.html", "")
    ))
    context = find_context(current_path)
    if context is None:
        return None
    if HEADER_END_MARKER not in original:
        raise BuildError(f"{rel_path}: matches context '{context.key}' but has no {HEADER_END_MARKER}")

    generated = render_nav(context, current_path)
    wrapped = f"{NAV_START}\n{generated}\n{NAV_END}"

    new_text = original
    marker_match = MARKER_PAIR_RE.search(new_text)
    bare_match = None if marker_match else BARE_NAV_RE.search(new_text)
    if marker_match:
        new_text = new_text[: marker_match.start()] + wrapped + new_text[marker_match.end() :]
    elif bare_match:
        replace_start = strip_preceding_comment(new_text, bare_match.start())
        new_text = new_text[:replace_start] + wrapped + new_text[bare_match.end() :]
    else:
        idx = new_text.find(HEADER_END_MARKER)
        insert_at = new_text.find("\n", idx)
        insert_at = insert_at + 1 if insert_at != -1 else idx + len(HEADER_END_MARKER)
        new_text = new_text[:insert_at] + "\n" + wrapped + "\n" + new_text[insert_at:]

    new_html_tag = set_editorial_context_attr(html_match.group(0), context.key)
    if new_html_tag != html_match.group(0):
        new_text = new_text.replace(html_match.group(0), new_html_tag, 1)

    return new_text


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="No escribe; falla si hay páginas desactualizadas")
    args = parser.parse_args()

    changed: list[str] = []
    touched = 0
    for path in sorted(tracked_html(ROOT)):
        rel = path.relative_to(ROOT).as_posix()
        if rel.startswith("lab/"):
            continue
        original = path.read_text(encoding="utf-8", errors="replace")
        try:
            new_text = apply_page(original, rel)
        except BuildError as exc:
            print(f"FAIL: {exc}", file=sys.stderr)
            return 1
        if new_text is None:
            continue
        touched += 1
        if new_text != original:
            changed.append(rel)
            if not args.check:
                path.write_text(new_text, encoding="utf-8")

    if args.check and changed:
        print("FAIL: section-context desactualizado en:", file=sys.stderr)
        for item in changed:
            print(f" - {item}", file=sys.stderr)
        return 1

    mode = "CHECK" if args.check else "GENERATED"
    print(f"{mode}: section-context evaluado en {touched} páginas con contexto")
    if changed:
        print(f"CHANGED: {len(changed)}")
        for item in changed:
            print(f" - {item}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except BuildError as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        raise SystemExit(1)
