// Helper for tests/test-ics-roundtrip-independent-parser.py: prints the ICS
// and JSON-LD generated by evento-escritor-core.js for a fixed model, so
// Python (icalendar + json.loads, both independent of the JS generator) can
// verify they actually parse -- not just that they match the generator's
// own structural assertions (already covered by
// tests/test-evento-ics-rfc5545.mjs).
import { buildEventOutputs } from '../../assets/evento-escritor-core.js';

const model = {
  name: 'Presentación de Las manecillas del recuerdo',
  confirmed: true,
  allDay: false,
  startDateTime: '2026-09-03T19:00',
  endDateTime: '2026-09-03T20:30',
  utcOffset: '+02:00',
  venueName: 'Librería de ejemplo — acentos: ñ á é ü',
  streetAddress: 'Calle Mayor 1',
  addressLocality: 'Madrid',
  addressRegion: 'Madrid',
  postalCode: '28013',
  addressCountry: 'España',
  url: 'https://davidportodiaz.com/eventos.html',
  description: 'Presentación con lectura de fragmentos; línea deliberadamente larga para forzar el plegado a 75 octetos y comprobar que al desplegar se reconstruye exactamente el texto original, incluidas las tildes y la ñ.',
};

const { ics, jsonLd } = buildEventOutputs(model);
console.log(JSON.stringify({ ics, jsonLd: typeof jsonLd === 'string' ? jsonLd : JSON.stringify(jsonLd) }));
